import mongoose from "mongoose";
import dotenv from "dotenv";

import Question from "./models/question.model.js";

dotenv.config();


const predefinedQuestions = [
    // 🚀 1. SOFTWARE ENGINEER (Easy Level)
    { jobRole: "Software Engineer", difficulty: "Easy", question: "What is a variable in programming?", correctAnswer: "A container that holds data.", keywords: ["variable", "data", "container"] },
    { jobRole: "Software Engineer", difficulty: "Easy", question: "What is an array?", correctAnswer: "A collection of elements stored in a single variable.", keywords: ["array", "collection", "elements"] },
    { jobRole: "Software Engineer", difficulty: "Easy", question: "What is a function?", correctAnswer: "A reusable block of code that performs a task.", keywords: ["function", "block", "code"] },
    { jobRole: "Software Engineer", difficulty: "Easy", question: "What is an object?", correctAnswer: "A collection of key-value pairs.", keywords: ["object", "key-value", "collection"] },
    { jobRole: "Software Engineer", difficulty: "Easy", question: "What is the difference between == and ===?", correctAnswer: "== checks value, === checks value and type.", keywords: ["==", "===", "value", "type"] },
    { jobRole: "Software Engineer", difficulty: "Easy", question: "What is a loop in programming?", correctAnswer: "A structure that repeats a block of code multiple times.", keywords: ["loop", "repeat", "code"] },
    { jobRole: "Software Engineer", difficulty: "Easy", question: "What is the purpose of a return statement?", correctAnswer: "It ends a function and returns a value.", keywords: ["return", "function", "value"] },
    { jobRole: "Software Engineer", difficulty: "Easy", question: "What is a class in object-oriented programming?", correctAnswer: "A template for creating objects.", keywords: ["class", "OOP", "template"] },
    { jobRole: "Software Engineer", difficulty: "Easy", question: "What is a method in programming?", correctAnswer: "A function inside a class.", keywords: ["method", "function", "class"] },
    { jobRole: "Software Engineer", difficulty: "Easy", question: "What is an algorithm?", correctAnswer: "A step-by-step procedure to solve a problem.", keywords: ["algorithm", "procedure", "problem"] },

    { jobRole: "Software Engineer", difficulty: "Medium", question: "What is the difference between synchronous and asynchronous programming?", correctAnswer: "Synchronous code executes sequentially, while asynchronous code allows execution without blocking.", keywords: ["synchronous", "asynchronous", "blocking", "execution"] },
    { jobRole: "Software Engineer", difficulty: "Medium", question: "What is a closure in JavaScript?", correctAnswer: "A function that remembers the scope in which it was created.", keywords: ["closure", "function", "scope"] },
    { jobRole: "Software Engineer", difficulty: "Medium", question: "What is memoization in programming?", correctAnswer: "An optimization technique that stores function results to avoid recomputation.", keywords: ["memoization", "optimization", "cache"] },
    { jobRole: "Software Engineer", difficulty: "Medium", question: "What is the difference between an abstract class and an interface?", correctAnswer: "An abstract class can have method implementations, while an interface only defines method signatures.", keywords: ["abstract class", "interface", "method signatures"] },
    { jobRole: "Software Engineer", difficulty: "Medium", question: "Explain Big-O notation.", correctAnswer: "A mathematical notation to describe the efficiency of an algorithm.", keywords: ["Big-O", "efficiency", "algorithm"] },
    { jobRole: "Software Engineer", difficulty: "Medium", question: "What is a REST API?", correctAnswer: "An API that follows REST principles using HTTP methods like GET, POST, PUT, DELETE.", keywords: ["REST API", "HTTP", "GET", "POST"] },
    { jobRole: "Software Engineer", difficulty: "Medium", question: "What is dependency injection?", correctAnswer: "A design pattern where dependencies are provided externally rather than created within a class.", keywords: ["dependency injection", "design pattern", "dependencies"] },
    { jobRole: "Software Engineer", difficulty: "Medium", question: "What are microservices?", correctAnswer: "An architectural style that structures an application as a collection of small services.", keywords: ["microservices", "architecture", "services"] },
    { jobRole: "Software Engineer", difficulty: "Medium", question: "What is a deadlock in multithreading?", correctAnswer: "A situation where two or more threads are blocked forever, waiting for each other.", keywords: ["deadlock", "multithreading", "blocked"] },
    { jobRole: "Software Engineer", difficulty: "Medium", question: "What is a race condition?", correctAnswer: "A condition where two threads access shared data at the same time, leading to unpredictable results.", keywords: ["race condition", "threads", "concurrency"] },

    { jobRole: "Software Engineer", difficulty: "Hard", question: "What is the difference between prototypal inheritance and classical inheritance?", correctAnswer: "Prototypal inheritance uses prototypes to share properties, while classical inheritance uses classes.", keywords: ["prototypal inheritance", "classical inheritance", "prototypes", "classes"] },
    { jobRole: "Software Engineer", difficulty: "Hard", question: "What is event delegation in JavaScript?", correctAnswer: "A technique where a single event listener is added to a parent element to manage events for its children.", keywords: ["event delegation", "JavaScript", "event listener", "parent element"] },
    { jobRole: "Software Engineer", difficulty: "Hard", question: "What is the purpose of the SOLID principles?", correctAnswer: "SOLID principles are design guidelines to create more understandable, flexible, and maintainable software.", keywords: ["SOLID", "design principles", "software", "maintainable"] },
    { jobRole: "Software Engineer", difficulty: "Hard", question: "What is the difference between a promise and an observable?", correctAnswer: "A promise handles a single asynchronous event, while an observable can handle multiple events over time.", keywords: ["promise", "observable", "asynchronous", "events"] },
    { jobRole: "Software Engineer", difficulty: "Hard", question: "What is the purpose of the 'use strict' directive in JavaScript?", correctAnswer: "'use strict' enforces stricter parsing and error handling in JavaScript code.", keywords: ["use strict", "JavaScript", "parsing", "error handling"] },
    { jobRole: "Software Engineer", difficulty: "Hard", question: "What is the difference between deep copy and shallow copy?", correctAnswer: "A deep copy duplicates all levels of an object, while a shallow copy only duplicates the top level.", keywords: ["deep copy", "shallow copy", "object", "duplicate"] },
    { jobRole: "Software Engineer", difficulty: "Hard", question: "What is the purpose of a service worker in web development?", correctAnswer: "A service worker intercepts network requests and can cache resources for offline use.", keywords: ["service worker", "web development", "network requests", "cache"] },
    { jobRole: "Software Engineer", difficulty: "Hard", question: "What is the difference between a monolithic and microservices architecture?", correctAnswer: "A monolithic architecture is a single, unified codebase, while microservices architecture consists of small, independent services.", keywords: ["monolithic", "microservices", "architecture", "codebase"] },
    { jobRole: "Software Engineer", difficulty: "Hard", question: "What is the difference between immutability and mutability in programming?", correctAnswer: "Immutability means an object's state cannot be changed after creation, while mutability allows changes.", keywords: ["immutability", "mutability", "object", "state"] },

// 🚀 2. DATA ANALYST (Easy Level)
{ jobRole: "Data Analyst", difficulty: "Easy", question: "What is SQL?", correctAnswer: "SQL is a language for managing databases.", keywords: ["SQL", "database", "query"] },
{ jobRole: "Data Analyst", difficulty: "Easy", question: "What is a primary key?", correctAnswer: "A unique identifier for a row in a table.", keywords: ["primary key", "unique", "identifier"] },
{ jobRole: "Data Analyst", difficulty: "Easy", question: "What is data visualization?", correctAnswer: "The graphical representation of data.", keywords: ["visualization", "graph", "representation"] },
{ jobRole: "Data Analyst", difficulty: "Easy", question: "What is the use of GROUP BY in SQL?", correctAnswer: "It groups rows sharing a property for aggregate functions.", keywords: ["GROUP BY", "aggregate", "function"] },
{ jobRole: "Data Analyst", difficulty: "Easy", question: "What is a foreign key?", correctAnswer: "A column that establishes a relationship between tables.", keywords: ["foreign key", "relationship", "tables"] },
{ jobRole: "Data Analyst", difficulty: "Easy", question: "What is data normalization?", correctAnswer: "A process to reduce redundancy in a database.", keywords: ["normalization", "redundancy", "database"] },
{ jobRole: "Data Analyst", difficulty: "Easy", question: "What is left join in SQL?", correctAnswer: "It returns all rows from the left table and matched rows from the right.", keywords: ["left join", "SQL", "tables"] },
{ jobRole: "Data Analyst", difficulty: "Easy", question: "What is the use of pivot tables?", correctAnswer: "They summarize large datasets in spreadsheets.", keywords: ["pivot table", "summarize", "spreadsheet"] },
{ jobRole: "Data Analyst", difficulty: "Easy", question: "What is ETL?", correctAnswer: "Extract, Transform, Load - a process in data warehousing.", keywords: ["ETL", "extract", "transform", "load"] },
{ jobRole: "Data Analyst", difficulty: "Easy", question: "What is a data pipeline?", correctAnswer: "A sequence of data processing steps.", keywords: ["data pipeline", "processing", "sequence"] },

// 🚀 3. DATA ANALYST (Medium Level)
{ jobRole: "Data Analyst", difficulty: "Medium", question: "What is data wrangling?", correctAnswer: "The process of cleaning, transforming, and organizing raw data into a usable format.", keywords: ["data wrangling", "cleaning", "transforming", "organizing"] },
{ jobRole: "Data Analyst", difficulty: "Medium", question: "What is ETL in data processing?", correctAnswer: "ETL stands for Extract, Transform, Load, a process used to integrate data from multiple sources.", keywords: ["ETL", "Extract", "Transform", "Load", "integration"] },
{ jobRole: "Data Analyst", difficulty: "Medium", question: "What is data mining?", correctAnswer: "The process of discovering patterns and insights from large datasets using statistical and machine learning techniques.", keywords: ["data mining", "patterns", "insights", "machine learning"] },
{ jobRole: "Data Analyst", difficulty: "Medium", question: "What is the difference between structured and unstructured data?", correctAnswer: "Structured data is organized in a predefined format like tables, while unstructured data lacks a specific format.", keywords: ["structured data", "unstructured data", "tables", "format"] },
{ jobRole: "Data Analyst", difficulty: "Medium", question: "What is the purpose of a data lake?", correctAnswer: "A data lake is a storage system that holds raw data in its native format until needed for analysis.", keywords: ["data lake", "storage", "raw data", "analysis"] },
{ jobRole: "Data Analyst", difficulty: "Medium", question: "What is a data mart?", correctAnswer: "A data mart is a subset of a data warehouse designed for a specific department or business unit.", keywords: ["data mart", "data warehouse", "business unit", "subset"] },
{ jobRole: "Data Analyst", difficulty: "Medium", question: "What are the advantages of using Python for data analysis?", correctAnswer: "Python offers powerful libraries like Pandas, NumPy, and Matplotlib for data manipulation, analysis, and visualization.", keywords: ["Python", "Pandas", "NumPy", "Matplotlib", "data analysis"] },
{ jobRole: "Data Analyst", difficulty: "Medium", question: "What is the difference between correlation and causation?", correctAnswer: "Correlation indicates a relationship between two variables, while causation means one variable directly affects the other.", keywords: ["correlation", "causation", "relationship", "variable"] },
{ jobRole: "Data Analyst", difficulty: "Medium", question: "What is hypothesis testing in data analysis?", correctAnswer: "A statistical method used to determine if there is enough evidence to support a given hypothesis.", keywords: ["hypothesis testing", "statistical method", "evidence", "analysis"] },
{ jobRole: "Data Analyst", difficulty: "Medium", question: "What is the difference between supervised and unsupervised learning?", correctAnswer: "Supervised learning uses labeled data to train models, while unsupervised learning finds patterns in unlabeled data.", keywords: ["supervised learning", "unsupervised learning", "labeled data", "patterns"] },

// 🚀 4. DATA ANALYST (Hard Level)
{ jobRole: "Data Analyst", difficulty: "Hard", question: "What is the difference between a data warehouse and a data lake?", correctAnswer: "A data warehouse stores structured data for analysis, while a data lake stores raw data in its native format.", keywords: ["data warehouse", "data lake", "structured data", "raw data"] },
{ jobRole: "Data Analyst", difficulty: "Hard", question: "What is the purpose of dimensional modeling in data warehousing?", correctAnswer: "Dimensional modeling organizes data into fact and dimension tables to optimize query performance.", keywords: ["dimensional modeling", "fact table", "dimension table", "query performance"] },
{ jobRole: "Data Analyst", difficulty: "Hard", question: "What is the difference between OLAP and OLTP?", correctAnswer: "OLAP is used for analytical queries on large datasets, while OLTP is used for transactional queries on operational data.", keywords: ["OLAP", "OLTP", "analytical queries", "transactional queries"] },
{ jobRole: "Data Analyst", difficulty: "Hard", question: "What is the purpose of a star schema in data warehousing?", correctAnswer: "A star schema simplifies complex queries by organizing data into fact and dimension tables.", keywords: ["star schema", "data warehousing", "fact table", "dimension table"] },
{ jobRole: "Data Analyst", difficulty: "Hard", question: "What is the difference between a data lake and a data mart?", correctAnswer: "A data lake stores raw data in its native format, while a data mart is a subset of a data warehouse focused on a specific business line.", keywords: ["data lake", "data mart", "raw data", "business line"] },
{ jobRole: "Data Analyst", difficulty: "Hard", question: "What is the purpose of a snowflake schema in data warehousing?", correctAnswer: "A snowflake schema normalizes dimension tables to reduce redundancy and improve data integrity.", keywords: ["snowflake schema", "data warehousing", "normalization", "data integrity"] },
{ jobRole: "Data Analyst", difficulty: "Hard", question: "What is the difference between batch processing and stream processing?", correctAnswer: "Batch processing handles large volumes of data at once, while stream processing handles data in real-time.", keywords: ["batch processing", "stream processing", "real-time", "data"] },
{ jobRole: "Data Analyst", difficulty: "Hard", question: "What is the purpose of data governance in an organization?", correctAnswer: "Data governance ensures data quality, security, and compliance with regulations.", keywords: ["data governance", "data quality", "security", "compliance"] },
{ jobRole: "Data Analyst", difficulty: "Hard", question: "What is the difference between a data scientist and a data analyst?", correctAnswer: "A data scientist focuses on advanced analytics and machine learning, while a data analyst focuses on interpreting and visualizing data.", keywords: ["data scientist", "data analyst", "analytics", "machine learning"] },
{ jobRole: "Data Analyst", difficulty: "Hard", question: "What is the purpose of a data catalog?", correctAnswer: "A data catalog organizes and provides metadata about data assets to improve data discovery and management.", keywords: ["data catalog", "metadata", "data discovery", "management"] },

    // 🚀 8. CLOUD ENGINEER (Easy Level)
    { jobRole: "Cloud Engineer", difficulty: "Easy", question: "What is cloud computing?", correctAnswer: "The delivery of computing services over the internet.", keywords: ["cloud computing", "internet", "services"] },
    { jobRole: "Cloud Engineer", difficulty: "Easy", question: "What are the three main cloud service models?", correctAnswer: "Infrastructure as a Service (IaaS), Platform as a Service (PaaS), and Software as a Service (SaaS).", keywords: ["IaaS", "PaaS", "SaaS", "service models"] },
    { jobRole: "Cloud Engineer", difficulty: "Easy", question: "What is scalability in cloud computing?", correctAnswer: "The ability of a system to handle increased workload by adding resources.", keywords: ["scalability", "handle workload", "resources"] },
    { jobRole: "Cloud Engineer", difficulty: "Easy", question: "What is a public cloud?", correctAnswer: "A cloud computing model where services are available to multiple users over the internet.", keywords: ["public cloud", "multiple users", "internet"] },
    { jobRole: "Cloud Engineer", difficulty: "Easy", question: "What is a private cloud?", correctAnswer: "A cloud environment dedicated to a single organization.", keywords: ["private cloud", "single organization", "security"] },
    { jobRole: "Cloud Engineer", difficulty: "Easy", question: "What is a Virtual Machine (VM)?", correctAnswer: "A software-based computer that runs an operating system and applications like a physical computer.", keywords: ["VM", "virtual machine", "software-based computer"] },
    { jobRole: "Cloud Engineer", difficulty: "Easy", question: "What is serverless computing?", correctAnswer: "A cloud computing execution model where cloud providers manage the infrastructure and dynamically allocate resources.", keywords: ["serverless computing", "cloud provider", "dynamic allocation"] },
    { jobRole: "Cloud Engineer", difficulty: "Easy", question: "What is cloud storage?", correctAnswer: "A service that allows users to store and manage data on remote servers accessed via the internet.", keywords: ["cloud storage", "remote servers", "data management"] },
    { jobRole: "Cloud Engineer", difficulty: "Easy", question: "What is the difference between cloud computing and traditional on-premises computing?", correctAnswer: "Cloud computing provides resources on demand via the internet, while on-premises computing requires physical infrastructure.", keywords: ["cloud computing", "on-premises", "internet", "physical infrastructure"] },
    { jobRole: "Cloud Engineer", difficulty: "Easy", question: "What is a Content Delivery Network (CDN)?", correctAnswer: "A network of servers that distribute content closer to users to improve speed and reliability.", keywords: ["CDN", "content delivery", "servers", "speed", "reliability"] },

    { jobRole: "Cloud Engineer", difficulty: "Medium", question: "What is cloud elasticity?", correctAnswer: "The ability of a cloud system to automatically scale resources based on demand.", keywords: ["cloud elasticity", "scale", "resources"] },
  { jobRole: "Cloud Engineer", difficulty: "Medium", question: "What is the difference between vertical and horizontal scaling in cloud computing?", correctAnswer: "Vertical scaling increases the power of a single instance, while horizontal scaling adds more instances.", keywords: ["vertical scaling", "horizontal scaling", "instances"] },
  { jobRole: "Cloud Engineer", difficulty: "Medium", question: "What is the Shared Responsibility Model in cloud computing?", correctAnswer: "A model that defines responsibilities between the cloud provider and the customer for security and maintenance.", keywords: ["shared responsibility", "cloud provider", "customer", "security"] },
  { jobRole: "Cloud Engineer", difficulty: "Medium", question: "What is a multi-cloud strategy?", correctAnswer: "A strategy where organizations use multiple cloud providers to avoid vendor lock-in and improve redundancy.", keywords: ["multi-cloud", "vendor lock-in", "redundancy", "providers"] },
  { jobRole: "Cloud Engineer", difficulty: "Medium", question: "What are containers in cloud computing?", correctAnswer: "Lightweight, standalone executable packages that include application code and dependencies.", keywords: ["containers", "Docker", "dependencies", "lightweight"] },
  { jobRole: "Cloud Engineer", difficulty: "Medium", question: "What is the difference between cloud storage and cloud computing?", correctAnswer: "Cloud storage is used for storing data, while cloud computing provides computing resources on demand.", keywords: ["cloud storage", "cloud computing", "resources", "data"] },
  { jobRole: "Cloud Engineer", difficulty: "Medium", question: "What is Infrastructure as Code (IaC)?", correctAnswer: "A method of managing infrastructure using code rather than manual configuration.", keywords: ["IaC", "Infrastructure as Code", "automation", "configuration"] },
  { jobRole: "Cloud Engineer", difficulty: "Medium", question: "What is an API Gateway in cloud computing?", correctAnswer: "A service that acts as an entry point for APIs, managing traffic and security.", keywords: ["API Gateway", "entry point", "traffic management", "security"] },
  { jobRole: "Cloud Engineer", difficulty: "Medium", question: "What is a cloud-based load balancer?", correctAnswer: "A service that distributes incoming network traffic across multiple servers to ensure availability.", keywords: ["load balancer", "traffic distribution", "availability", "servers"] },
  { jobRole: "Cloud Engineer", difficulty: "Medium", question: "What is serverless architecture in cloud computing?", correctAnswer: "An architecture where developers can run applications without managing infrastructure.", keywords: ["serverless", "no infrastructure", "cloud computing", "event-driven"] },

  { jobRole: "Cloud Engineer", difficulty: "Hard", question: "What is Chaos Engineering, and how is it applied in cloud computing?", correctAnswer: "Chaos Engineering is a discipline that helps build resilient systems by proactively testing failures in a controlled environment.", keywords: ["Chaos Engineering", "resilient systems", "failure testing", "controlled environment"] },
  { jobRole: "Cloud Engineer", difficulty: "Hard", question: "How does Kubernetes handle high availability in a cloud environment?", correctAnswer: "Kubernetes ensures high availability using multiple master nodes, auto-scaling, and load balancing across worker nodes.", keywords: ["Kubernetes", "high availability", "master nodes", "auto-scaling"] },
  { jobRole: "Cloud Engineer", difficulty: "Hard", question: "What is a service mesh, and how does it enhance cloud networking?", correctAnswer: "A service mesh is a dedicated infrastructure layer that manages service-to-service communication, improving security, observability, and traffic control.", keywords: ["service mesh", "cloud networking", "service-to-service communication", "observability"] },
  { jobRole: "Cloud Engineer", difficulty: "Hard", question: "What are the key security risks of multi-cloud environments?", correctAnswer: "Security risks include data inconsistency, API vulnerabilities, lack of centralized monitoring, and compliance challenges.", keywords: ["multi-cloud", "security risks", "API vulnerabilities", "compliance challenges"] },
  { jobRole: "Cloud Engineer", difficulty: "Hard", question: "Explain the concept of FinOps in cloud cost management.", correctAnswer: "FinOps is a cloud financial management practice that helps organizations optimize cloud costs through collaboration between finance, engineering, and operations teams.", keywords: ["FinOps", "cloud cost management", "finance", "optimization"] },
  { jobRole: "Cloud Engineer", difficulty: "Hard", question: "What is the CAP theorem, and how does it apply to cloud databases?", correctAnswer: "The CAP theorem states that a distributed system can only achieve two out of three properties: Consistency, Availability, and Partition Tolerance.", keywords: ["CAP theorem", "distributed systems", "consistency", "availability", "partition tolerance"] },
  { jobRole: "Cloud Engineer", difficulty: "Hard", question: "How does serverless computing differ from traditional cloud architectures in terms of scalability?", correctAnswer: "Serverless computing automatically scales based on demand, while traditional architectures require manual or auto-scaling configurations.", keywords: ["serverless computing", "scalability", "auto-scaling", "traditional cloud"] },
  { jobRole: "Cloud Engineer", difficulty: "Hard", question: "What is the significance of edge computing in cloud architecture?", correctAnswer: "Edge computing processes data closer to the source, reducing latency and bandwidth usage while improving real-time processing capabilities.", keywords: ["edge computing", "latency", "bandwidth", "real-time processing"] },
  { jobRole: "Cloud Engineer", difficulty: "Hard", question: "What is the difference between Stateful and Stateless applications in the cloud?", correctAnswer: "Stateful applications store session data across requests, while stateless applications do not retain session data and rely on external storage.", keywords: ["stateful", "stateless", "session data", "cloud applications"] },
  { jobRole: "Cloud Engineer", difficulty: "Hard", question: "What strategies can be used to migrate a monolithic application to a cloud-native microservices architecture?", correctAnswer: "Strategies include the Strangler Fig pattern, Domain-Driven Design, API gateway implementation, and containerization.", keywords: ["monolithic", "cloud-native", "microservices", "migration strategies"] },
  

    { jobRole: "Network Engineer", difficulty: "Easy", question: "What is networking?", correctAnswer: "The practice of connecting computers and other devices to share resources and data.", keywords: ["networking", "connect", "computers", "share data"] },
  { jobRole: "Network Engineer", difficulty: "Easy", question: "What is an IP address?", correctAnswer: "A unique identifier assigned to each device on a network.", keywords: ["IP address", "identifier", "network", "device"] },
  { jobRole: "Network Engineer", difficulty: "Easy", question: "What is a router?", correctAnswer: "A device that forwards data packets between computer networks.", keywords: ["router", "data packets", "computer networks"] },
  { jobRole: "Network Engineer", difficulty: "Easy", question: "What is the function of a switch in networking?", correctAnswer: "A switch connects devices within a network and forwards data to the correct destination.", keywords: ["switch", "connect devices", "forward data"] },
  { jobRole: "Network Engineer", difficulty: "Easy", question: "What is the difference between IPv4 and IPv6?", correctAnswer: "IPv4 uses a 32-bit address scheme, whereas IPv6 uses a 128-bit address scheme.", keywords: ["IPv4", "IPv6", "32-bit", "128-bit"] },
  { jobRole: "Network Engineer", difficulty: "Easy", question: "What is a subnet?", correctAnswer: "A segment of a network that improves performance and security.", keywords: ["subnet", "segment", "network", "performance", "security"] },
  { jobRole: "Network Engineer", difficulty: "Easy", question: "What is a MAC address?", correctAnswer: "A unique hardware identifier assigned to network interfaces.", keywords: ["MAC address", "hardware", "identifier", "network interface"] },
  { jobRole: "Network Engineer", difficulty: "Easy", question: "What is DNS (Domain Name System)?", correctAnswer: "A system that translates domain names into IP addresses.", keywords: ["DNS", "domain name", "IP address", "translate"] },
  { jobRole: "Network Engineer", difficulty: "Easy", question: "What is the difference between TCP and UDP?", correctAnswer: "TCP is connection-oriented and reliable, while UDP is connectionless and faster.", keywords: ["TCP", "UDP", "connection-oriented", "connectionless", "reliable"] },
  { jobRole: "Network Engineer", difficulty: "Easy", question: "What is a VLAN?", correctAnswer: "A Virtual Local Area Network that segments a network to improve efficiency and security.", keywords: ["VLAN", "Virtual LAN", "network segmentation", "security"] },

  { jobRole: "Network Engineer", difficulty: "Medium", question: "What is subnetting, and why is it used?", correctAnswer: "Subnetting is the process of dividing a large network into smaller sub-networks to improve efficiency and security.", keywords: ["subnetting", "network division", "efficiency", "security"] },
  { jobRole: "Network Engineer", difficulty: "Medium", question: "What is the difference between a hub, a switch, and a router?", correctAnswer: "A hub broadcasts data to all devices, a switch forwards data to specific devices, and a router connects different networks.", keywords: ["hub", "switch", "router", "networking"] },
  { jobRole: "Network Engineer", difficulty: "Medium", question: "What is the purpose of the OSI model?", correctAnswer: "The OSI model standardizes network communication into seven layers to ensure interoperability between systems.", keywords: ["OSI model", "network layers", "communication", "standardization"] },
  { jobRole: "Network Engineer", difficulty: "Medium", question: "What is a VLAN (Virtual Local Area Network)?", correctAnswer: "A VLAN is a logical network that allows devices to be grouped together virtually, improving security and efficiency.", keywords: ["VLAN", "logical network", "security", "efficiency"] },
  { jobRole: "Network Engineer", difficulty: "Medium", question: "What is NAT (Network Address Translation) and how does it work?", correctAnswer: "NAT translates private IP addresses into a public IP address for internet communication.", keywords: ["NAT", "network address translation", "IP address", "internet"] },
  { jobRole: "Network Engineer", difficulty: "Medium", question: "What is the difference between TCP and UDP?", correctAnswer: "TCP is connection-oriented and reliable, while UDP is connectionless and faster.", keywords: ["TCP", "UDP", "connection-oriented", "connectionless", "reliable"] },
  { jobRole: "Network Engineer", difficulty: "Medium", question: "What are the different types of network topologies?", correctAnswer: "Common network topologies include star, bus, ring, and mesh, each with unique advantages and use cases.", keywords: ["network topology", "star", "bus", "ring", "mesh"] },
  { jobRole: "Network Engineer", difficulty: "Medium", question: "What is a DMZ (Demilitarized Zone) in networking?", correctAnswer: "A DMZ is a network segment that acts as a buffer zone between a private network and an external network like the internet.", keywords: ["DMZ", "demilitarized zone", "buffer", "network security"] },
  { jobRole: "Network Engineer", difficulty: "Medium", question: "What is BGP (Border Gateway Protocol)?", correctAnswer: "BGP is a protocol used to exchange routing information between different autonomous systems on the internet.", keywords: ["BGP", "routing", "autonomous system", "internet"] },
  { jobRole: "Network Engineer", difficulty: "Medium", question: "What is the difference between IPv4 and IPv6?", correctAnswer: "IPv4 uses a 32-bit address space, while IPv6 uses a 128-bit address space, providing more available addresses.", keywords: ["IPv4", "IPv6", "address space", "networking"] },

  { jobRole: "Network Engineer", difficulty: "Hard", question: "What is BGP hijacking, and how can it be prevented?", correctAnswer: "BGP hijacking is a malicious attack where a network misleads other networks about the best route for data. It can be prevented using RPKI, route filtering, and monitoring tools.", keywords: ["BGP hijacking", "malicious attack", "RPKI", "route filtering"] },
  { jobRole: "Network Engineer", difficulty: "Hard", question: "Explain the differences between OSPF and EIGRP routing protocols.", correctAnswer: "OSPF is a link-state protocol that uses Dijkstra’s algorithm, while EIGRP is a hybrid protocol that uses the Diffusing Update Algorithm (DUAL).", keywords: ["OSPF", "EIGRP", "link-state", "DUAL algorithm"] },
  { jobRole: "Network Engineer", difficulty: "Hard", question: "What is the purpose of QoS (Quality of Service) in networking?", correctAnswer: "QoS prioritizes network traffic to ensure high performance for critical applications, reducing latency, jitter, and packet loss.", keywords: ["QoS", "network traffic", "latency", "packet loss"] },
  { jobRole: "Network Engineer", difficulty: "Hard", question: "What is a GRE tunnel, and how is it different from an IPsec tunnel?", correctAnswer: "A GRE tunnel encapsulates any Layer 3 protocol but lacks encryption, while an IPsec tunnel provides secure, encrypted connections.", keywords: ["GRE tunnel", "IPsec", "encapsulation", "encryption"] },
  { jobRole: "Network Engineer", difficulty: "Hard", question: "How does MPLS (Multiprotocol Label Switching) improve network performance?", correctAnswer: "MPLS uses label switching to forward packets efficiently, reducing latency and improving QoS.", keywords: ["MPLS", "label switching", "latency", "QoS"] },
  { jobRole: "Network Engineer", difficulty: "Hard", question: "What is the difference between Layer 2 and Layer 3 switches?", correctAnswer: "A Layer 2 switch operates at the data link layer and forwards frames based on MAC addresses, while a Layer 3 switch operates at the network layer and routes packets based on IP addresses.", keywords: ["Layer 2 switch", "Layer 3 switch", "MAC address", "IP address"] },
  { jobRole: "Network Engineer", difficulty: "Hard", question: "What are the main security risks associated with IPv6 adoption?", correctAnswer: "IPv6 security risks include address spoofing, rogue RA attacks, lack of mature firewall support, and tunneling vulnerabilities.", keywords: ["IPv6", "security risks", "address spoofing", "tunneling vulnerabilities"] },
  { jobRole: "Network Engineer", difficulty: "Hard", question: "What is network segmentation, and why is it important for security?", correctAnswer: "Network segmentation divides a network into smaller sections to contain security breaches and reduce lateral movement of threats.", keywords: ["network segmentation", "security", "lateral movement", "containment"] },
  { jobRole: "Network Engineer", difficulty: "Hard", question: "How do SDN (Software-Defined Networking) and traditional networking differ?", correctAnswer: "SDN separates the control and data planes, enabling centralized network management, while traditional networking relies on distributed control.", keywords: ["SDN", "Software-Defined Networking", "control plane", "data plane"] },
  { jobRole: "Network Engineer", difficulty: "Hard", question: "What techniques can be used to optimize network redundancy and failover mechanisms?", correctAnswer: "Techniques include using BGP failover, redundant links, load balancing, VRRP, and HSRP.", keywords: ["network redundancy", "failover", "BGP failover", "VRRP", "HSRP"] },

  { jobRole: "System Administrator", difficulty: "Easy", question: "What is the role of a System Administrator?", correctAnswer: "A System Administrator is responsible for managing and maintaining computer systems and networks.", keywords: ["System Administrator", "manage", "maintain", "computer systems", "networks"] },
  { jobRole: "System Administrator", difficulty: "Easy", question: "What is an operating system?", correctAnswer: "Software that manages computer hardware and software resources.", keywords: ["operating system", "OS", "hardware", "software"] },
  { jobRole: "System Administrator", difficulty: "Easy", question: "What is Active Directory?", correctAnswer: "A Microsoft service that manages users and computers in a network.", keywords: ["Active Directory", "Microsoft", "manage", "users", "network"] },
  { jobRole: "System Administrator", difficulty: "Easy", question: "What is the purpose of a backup?", correctAnswer: "A backup ensures data is protected in case of data loss or system failure.", keywords: ["backup", "data protection", "restore", "system failure"] },
  { jobRole: "System Administrator", difficulty: "Easy", question: "What is the difference between a local user and a domain user?", correctAnswer: "A local user account is limited to one machine, whereas a domain user account can access network resources.", keywords: ["local user", "domain user", "network resources"] },
  { jobRole: "System Administrator", difficulty: "Easy", question: "What is a VPN?", correctAnswer: "A Virtual Private Network allows secure access to a private network over the internet.", keywords: ["VPN", "Virtual Private Network", "secure", "internet"] },
  { jobRole: "System Administrator", difficulty: "Easy", question: "What is disk partitioning?", correctAnswer: "The process of dividing a hard disk into multiple storage areas.", keywords: ["disk partitioning", "hard disk", "storage"] },
  { jobRole: "System Administrator", difficulty: "Easy", question: "What is a proxy server?", correctAnswer: "A proxy server acts as an intermediary between a client and the internet.", keywords: ["proxy server", "intermediary", "client", "internet"] },
  { jobRole: "System Administrator", difficulty: "Easy", question: "What is a service pack?", correctAnswer: "A collection of updates and fixes for an operating system or software.", keywords: ["service pack", "updates", "fixes", "operating system"] },
  { jobRole: "System Administrator", difficulty: "Easy", question: "What is system monitoring?", correctAnswer: "The process of tracking system performance, usage, and health.", keywords: ["system monitoring", "performance", "usage", "health"] },

    { jobRole: "System Administrator", difficulty: "Medium", question: "What is RAID (Redundant Array of Independent Disks)?", correctAnswer: "RAID is a storage technology that combines multiple disks for performance, redundancy, or both.", keywords: ["RAID", "storage technology", "disks", "performance", "redundancy"] },
    { jobRole: "System Administrator", difficulty: "Medium", question: "What is the difference between a backup and an archive?", correctAnswer: "A backup is a copy of data for recovery, while an archive stores data for long-term retention.", keywords: ["backup", "archive", "recovery", "long-term retention"] },
    { jobRole: "System Administrator", difficulty: "Medium", question: "What is a DHCP server?", correctAnswer: "A server that assigns IP addresses to devices on a network automatically.", keywords: ["DHCP server", "IP addresses", "network", "automatic assignment"] },
    { jobRole: "System Administrator", difficulty: "Medium", question: "What is a cron job?", correctAnswer: "A scheduled task that runs at specific intervals on Unix-based systems.", keywords: ["cron job", "scheduled task", "intervals", "Unix"] },
    { jobRole: "System Administrator", difficulty: "Medium", question: "What is a container in system administration?", correctAnswer: "A lightweight, standalone package that includes everything needed to run a piece of software.", keywords: ["container", "lightweight", "standalone", "software"] },
    { jobRole: "System Administrator", difficulty: "Medium", question: "What is the purpose of a firewall in system security?", correctAnswer: "A firewall filters network traffic to prevent unauthorized access and protect against cyber threats.", keywords: ["firewall", "network traffic", "security", "cyber threats"] },
    { jobRole: "System Administrator", difficulty: "Medium", question: "What is a reverse proxy?", correctAnswer: "A server that retrieves resources on behalf of clients from one or more servers.", keywords: ["reverse proxy", "server", "resources", "clients"] },
    { jobRole: "System Administrator", difficulty: "Medium", question: "What is the difference between a full backup and an incremental backup?", correctAnswer: "A full backup copies all data, while an incremental backup copies changes since the last backup.", keywords: ["full backup", "incremental backup", "data", "changes"] },
    { jobRole: "System Administrator", difficulty: "Medium", question: "What is a network protocol?", correctAnswer: "A set of rules that govern data communication between devices on a network.", keywords: ["network protocol", "rules", "data communication", "devices"] },
    { jobRole: "System Administrator", difficulty: "Medium", question: "What is a disaster recovery plan?", correctAnswer: "A documented process to recover IT systems and data after a disaster.", keywords: ["disaster recovery plan", "recovery", "IT systems", "data"] },

    { jobRole: "System Administrator", difficulty: "Hard", question: "What is the difference between a hypervisor Type 1 and Type 2?", correctAnswer: "A Type 1 hypervisor runs directly on hardware (bare-metal), while a Type 2 hypervisor runs on an operating system.", keywords: ["hypervisor", "Type 1", "Type 2", "bare-metal", "operating system"] },
    { jobRole: "System Administrator", difficulty: "Hard", question: "How do you secure an Active Directory environment?", correctAnswer: "By implementing least privilege access, enabling auditing, using strong password policies, and enabling multi-factor authentication.", keywords: ["Active Directory", "security", "least privilege", "MFA", "auditing"] },
    { jobRole: "System Administrator", difficulty: "Hard", question: "What are the key differences between RAID 0, RAID 1, RAID 5, and RAID 10?", correctAnswer: "RAID 0 offers striping without redundancy, RAID 1 mirrors data, RAID 5 provides redundancy with parity, and RAID 10 combines mirroring and striping.", keywords: ["RAID 0", "RAID 1", "RAID 5", "RAID 10", "redundancy"] },
    { jobRole: "System Administrator", difficulty: "Hard", question: "What is the significance of Kerberos authentication in Windows systems?", correctAnswer: "Kerberos is a secure protocol that uses ticket-based authentication to prevent password transmission over the network.", keywords: ["Kerberos", "authentication", "ticket-based", "security", "Windows"] },
    { jobRole: "System Administrator", difficulty: "Hard", question: "How would you recover a compromised root account on a Linux server?", correctAnswer: "Boot into single-user mode, remount the filesystem with write permissions, reset the root password, and reboot the system.", keywords: ["Linux", "root account recovery", "single-user mode", "reset password"] },
    { jobRole: "System Administrator", difficulty: "Hard", question: "What are the best practices for securing a Linux server?", correctAnswer: "Use SSH key authentication, disable root login, enable firewall rules, keep software updated, and implement SELinux/AppArmor.", keywords: ["Linux security", "SSH", "firewall", "SELinux", "AppArmor"] },
    { jobRole: "System Administrator", difficulty: "Hard", question: "How do you diagnose and resolve a memory leak issue on a server?", correctAnswer: "Use tools like `top`, `htop`, `free`, and `valgrind` to monitor memory usage, identify faulty processes, and optimize memory allocation.", keywords: ["memory leak", "diagnosis", "server", "top", "valgrind"] },
    { jobRole: "System Administrator", difficulty: "Hard", question: "Explain the role of Syslog in system administration.", correctAnswer: "Syslog is a logging protocol used to collect and store system logs for security monitoring and troubleshooting.", keywords: ["Syslog", "logging", "monitoring", "troubleshooting", "security"] },
    { jobRole: "System Administrator", difficulty: "Hard", question: "What are the advantages and disadvantages of using containers over virtual machines?", correctAnswer: "Containers offer lightweight, fast deployment but provide less isolation than VMs, which have dedicated OS environments.", keywords: ["containers", "virtual machines", "deployment", "isolation", "OS"] },
    { jobRole: "System Administrator", difficulty: "Hard", question: "How do you automate server configuration management?", correctAnswer: "Use tools like Ansible, Puppet, or Chef to automate configuration, apply security policies, and maintain consistency.", keywords: ["automation", "server configuration", "Ansible", "Puppet", "Chef"] },


    { jobRole: "MERN Stack Developer", difficulty: "Easy", question: "What does MERN stand for?", correctAnswer: "MERN stands for MongoDB, Express.js, React, and Node.js.", keywords: ["MERN", "MongoDB", "Express.js", "React", "Node.js"] },
    { jobRole: "MERN Stack Developer", difficulty: "Easy", question: "What is the purpose of Express.js in MERN Stack?", correctAnswer: "Express.js is a web framework for Node.js used to build server-side applications and APIs.", keywords: ["Express.js", "web framework", "server-side", "API"] },
    { jobRole: "MERN Stack Developer", difficulty: "Easy", question: "What is JSX in React?", correctAnswer: "JSX is a syntax extension that allows writing HTML-like code inside JavaScript.", keywords: ["JSX", "React", "syntax extension", "HTML-like"] },
    { jobRole: "MERN Stack Developer", difficulty: "Easy", question: "What is the role of MongoDB in MERN Stack?", correctAnswer: "MongoDB is a NoSQL database that stores data in JSON-like documents.", keywords: ["MongoDB", "NoSQL", "JSON", "database"] },
    { jobRole: "MERN Stack Developer", difficulty: "Easy", question: "What is the use of props in React?", correctAnswer: "Props allow passing data from parent to child components in React.", keywords: ["props", "React", "parent-child", "data passing"] },
    { jobRole: "MERN Stack Developer", difficulty: "Easy", question: "How do you start a Node.js server?", correctAnswer: "By using the built-in http module or Express.js with `app.listen(port)`. ", keywords: ["Node.js", "server", "http", "Express.js"] },
    { jobRole: "MERN Stack Developer", difficulty: "Easy", question: "What is useState in React?", correctAnswer: "useState is a React Hook that allows functional components to manage state.", keywords: ["useState", "React Hook", "state management"] },
    { jobRole: "MERN Stack Developer", difficulty: "Easy", question: "What command is used to install dependencies in a Node.js project?", correctAnswer: "The `npm install` or `yarn install` command.", keywords: ["npm install", "yarn install", "dependencies", "Node.js"] },
    { jobRole: "MERN Stack Developer", difficulty: "Easy", question: "What is the purpose of package.json in a Node.js project?", correctAnswer: "It contains metadata about the project and lists dependencies.", keywords: ["package.json", "metadata", "dependencies"] },
    { jobRole: "MERN Stack Developer", difficulty: "Easy", question: "What is middleware in Express.js?", correctAnswer: "Middleware functions modify request and response objects before reaching the final handler.", keywords: ["middleware", "Express.js", "request", "response"] },

    { jobRole: "MERN Stack Developer", difficulty: "Medium", question: "What is the difference between state and props in React?", correctAnswer: "State is local to a component, while props are passed from parent to child components.", keywords: ["state", "props", "React", "local"] },
  { jobRole: "MERN Stack Developer", difficulty: "Medium", question: "How do you handle forms in React?", correctAnswer: "Forms in React are handled using controlled or uncontrolled components.", keywords: ["forms", "React", "controlled", "uncontrolled"] },
  { jobRole: "MERN Stack Developer", difficulty: "Medium", question: "What is RESTful API and how does it work?", correctAnswer: "RESTful API follows REST principles and uses HTTP methods to interact with data.", keywords: ["RESTful API", "HTTP methods", "CRUD"] },
  { jobRole: "MERN Stack Developer", difficulty: "Medium", question: "What are React Hooks? Name a few commonly used hooks.", correctAnswer: "Hooks allow functional components to use state and lifecycle methods. Examples: useState, useEffect, useContext.", keywords: ["React Hooks", "useState", "useEffect", "useContext"] },
  { jobRole: "MERN Stack Developer", difficulty: "Medium", question: "How does authentication work in MERN Stack?", correctAnswer: "Authentication is handled using JWT or sessions with bcrypt for password hashing.", keywords: ["authentication", "JWT", "bcrypt", "sessions"] },
  { jobRole: "MERN Stack Developer", difficulty: "Medium", question: "How do you connect a React frontend with an Express backend?", correctAnswer: "Using Axios or Fetch API to make HTTP requests from React to Express routes.", keywords: ["React", "Express.js", "Axios", "Fetch API"] },
  { jobRole: "MERN Stack Developer", difficulty: "Medium", question: "What is the purpose of Redux in a React application?", correctAnswer: "Redux is a state management library that helps manage global state across components.", keywords: ["Redux", "state management", "global state"] },
  { jobRole: "MERN Stack Developer", difficulty: "Medium", question: "What is the difference between useEffect and useState in React?", correctAnswer: "useState manages state, while useEffect handles side effects like API calls.", keywords: ["useEffect", "useState", "side effects", "API calls"] },
  { jobRole: "MERN Stack Developer", difficulty: "Medium", question: "How does Express handle routing?", correctAnswer: "Express uses `app.get()`, `app.post()`, and other HTTP methods to define routes.", keywords: ["Express.js", "routing", "app.get", "app.post"] },
  { jobRole: "MERN Stack Developer", difficulty: "Medium", question: "What is Mongoose, and why is it used in MongoDB?", correctAnswer: "Mongoose is an ODM library that provides schema-based data modeling for MongoDB.", keywords: ["Mongoose", "ODM", "schema", "MongoDB"] },

  { jobRole: "MERN Stack Developer", difficulty: "Hard", question: "What are React Fiber and Concurrent Mode?", correctAnswer: "React Fiber is a new reconciliation algorithm, and Concurrent Mode allows React to work on multiple tasks simultaneously.", keywords: ["React Fiber", "Concurrent Mode", "reconciliation"] },
  { jobRole: "MERN Stack Developer", difficulty: "Hard", question: "How do you optimize performance in a large-scale React application?", correctAnswer: "Using lazy loading, memoization, PureComponent, and virtualization.", keywords: ["performance", "lazy loading", "memoization", "virtualization"] },
  { jobRole: "MERN Stack Developer", difficulty: "Hard", question: "What is server-side rendering (SSR) and how does it improve performance?", correctAnswer: "SSR renders React components on the server before sending HTML to the client.", keywords: ["SSR", "server-side rendering", "performance"] },
  { jobRole: "MERN Stack Developer", difficulty: "Hard", question: "How do you handle race conditions in JavaScript?", correctAnswer: "Using promises, async/await, mutexes, or debouncing.", keywords: ["race conditions", "JavaScript", "async/await", "mutex"] },
  { jobRole: "MERN Stack Developer", difficulty: "Hard", question: "What is GraphQL, and how does it compare to REST?", correctAnswer: "GraphQL is a query language that allows clients to specify the data they need, unlike REST which has fixed endpoints.", keywords: ["GraphQL", "REST", "query language"] },

];




// const seedDB = async () => {
//  // await Question.deleteMany({}); // Clear existing data

//   await Question.insertMany(predefinedQuestions);

//   console.log("Database seeded with predefined questions!");
//   mongoose.connection.close();
// };

// seedDB();
